theme: jekyll-theme-primer
author: Sotiris Liagas
email: liagason@gmail.com
title: Sotiris Liagas
description: Personal homepage of Sotiris Liagas - Η προσωπική ιστοσελίδα του Σωτήρη Λιάγκα
twitter_username: liagason
github_username: liagason
permalink: /:title
