# Site Info
title:              "Sotiris Liagkas"
description:        "Sotiris Liagkas' personal homepage. Programming stuff."
author_name:        "Sotiris Liagkas"

# Site Settings
url:                https://liagason.com
baseurl:            /
permalink:          /:title
timezone:           Europe/Athens

# Site Build
markdown:           kramdown
kramdown:
    input:          GFM

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
