theme: jekyll-theme-primer
author: Sotiris Liagas
email: liagason@gmail.com
title: Sotiris Liagas
description: Sotiris Liagas personal homepage - Σωτήρης Λιάγκας
twitter_username: liagason
github_username: liagason
permalink: /:title
